CREATE TABLE CIDADE (
 ID_CIDADE INT IDENTITY NOT NULL ,
 NOME_CIDADE VARCHAR(50) ,
 UF_CIDADE CHAR(2) ,
PRIMARY KEY(ID_CIDADE));



CREATE TABLE CONTATO (
 ID_CONTATO INT IDENTITY NOT NULL ,
 NOME_CONTATO VARCHAR(50) NOT NULL ,
 END_CONTATO VARCHAR(100) NOT NULL ,
 CIDADE_ID_CIDADE INT NOT NULL ,
 CEL_CONTATO VARCHAR(15) NOT NULL ,
 EMAIL_CONTATO VARCHAR(100) NOT NULL ,
 DTCADASTRO_CONTATO DATE NOT NULL,
PRIMARY KEY(ID_CONTATO) ,
 FOREIGN KEY(CIDADE_ID_CIDADE)
 REFERENCES CIDADE(ID_CIDADE));